version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: src/Dockerfile  # Specify correct path
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: 
      context: ./PersonalFinanceTracker  # Ensure correct path
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db  # If using MySQL inside Docker
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=manager
      - DB_NAME=finance_tracker
    depends_on:
      db:
        condition: service_healthy  # Ensures DB is ready before starting backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: finance_tracker
    ports:
      - "3307:3306"  # Change host port to 3307 to avoid conflicts
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:  # Ensures MySQL is ready before backend starts
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
